=== datakaveri/iudx-adaptor-framework/server/src/main/resources/onboardingRulesSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#", 
    "type": "object",
    "additionalProperties": false,
	"required": [
		"name",
		"adaptorType",
		"inputSpec",
		"publishSpec"
	],
	"properties": {
		"name": {
            "title": "Name", 
			"type": "string",
			"default": ""
        },
		"adaptorType": {
            "title": "Adaptor Type", 
			"type": "string",
            "pattern": "^.*$"
		},
		"inputSpec": {
            "title": "Input Spec", 
			"type": "object",
			"required": [
				"type",
				"uri",
				"queueName",
				"sourceId",
				"parseSpec"
			],
			"properties": {
				"type": {
                    "title": "Type", 
					"type": "string"
                },
				"uri": {
                    "title": "Uri", 
					"type": "string",
					"default": ""
                },
				"queueName": {
                    "title": "Queue Name", 
					"type": "string",
					"default": ""
                },
				"sourceId": {
                    "title": "Source ID", 
					"type": "string"
                },
				"parseSpec": {
                    "title": "Parse Spec", 
					"type": "object",
					"required": [
						"type",
						"messageContainer",
						"timestampPath",
						"staticKey"
					],
					"properties": {
						"type": {
                            "title": "Type", 
							"type": "string",
							"default": ""
						},
						"messageContainer": {
                          "title": "Message Container", 
							"type": "string"
						},
						"timestampPath": {
                            "title": "Timestamp Path", 
							"type": "string"
                        },
						"staticKey": {
                            "title": "Static Key", 
							"type": "string"
						}
					}
				}
			}
		},
        "failureRecoverySpec": {
            "title": "Failure Recovery Spec",
            "type": "object",
            "optional": true,
            "properties": {
              "type": {
                "title": "Type",
                "type": "string",
                "optional": true
              },
              "initialBackoff": {
                "title": "Initial Backoff",
                "type": "integer"
              },
              "maxBackOff": {
                "title": "Max Backoff",
                "type": "integer"
              },
              "backoffMultiplier": {
                "title": "Backoff Multiplier",
                "type": "integer"
              },
              "resetBackpffThreshold": {
                "title": "Reset Backoff Threshold",
                "type": "integer"
              },
              "jitterFactor": {
                "title": "Jitter Factor",
                "type": "integer" 
              }
            }
        },
		"publishSpec": {
            "title": "Publish Spec", 
			"type": "object",
			"required": [
				"type",
				"uri"
			],
			"properties": {
				"type": {
                    "title": "Type", 
					"type": "string",
					"default": ""
                },
				"uri": {
                    "title": "Uri", 
					"type": "string",
					"default": ""
                }
			}
		}
	}
}

=== datakaveri/iudx-adaptor-framework/demo/ruleJobLocal.json
{
    "name": "rulejobLocal8",
    "adaptorType": "RULES",
    "inputSpec": {
      "type": "rmq",
      "uri": "amqp://guest:guest@rmq:5672/%2F",
      "queueName": "adaptor-test",
      "sourceId": "surat-itms",
      "parseSpec": {
        "type": "json",
        "messageContainer": "single",
        "timestampPath": "$.observationDateTime",
        "staticKey": "rules"
      }
    },
    "publishSpec": {
      "type": "rmq",
      "uri": "amqp://guest:guest@rmq:5672/%2F"
    }
  }
